name: Cron Check Markdown Links

on:
  schedule:
    - cron: "0 0 * * 0" # Once a week on Sunday

jobs:
  link-check:
    strategy:
      matrix:
        file-extension: [.md]
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: '.mlc_config.json'
        #check-modified-files-only: 'yes'
        folder-path: 'docs'