name: Validate Markdown

on:
  pull_request:
    paths:
      - 'docs/**'

jobs:
  markdown-lint:
    name: Markdown Lint CLI
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: nosborn/github-action-markdown-cli@v3.2.0
        with:
          files: 'docs'
          config_file: ".markdownlint.json"